packages:
  - apps/*
  - packages/*
  - services/api

ignoredBuiltDependencies:
  - '@nestjs/core'
  - msgpackr-extract
  - unrs-resolver

onlyBuiltDependencies:
  - prisma
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
