module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  testPathIgnorePatterns: ['/node_modules/', '/dist/', '/src/integration/'],
  // pnpm: resolve modules from package and workspace root
  moduleDirectories: ['node_modules', '<rootDir>/../../node_modules'],
  transform: {
    '^.+\\.(t|j)s$': ['ts-jest', {
      isolatedModules: true,
    }],
  },
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/*.spec.ts',
    '!**/*.module.ts',
    '!**/*.controller.ts',
    '!**/*.dto.ts',
    '!**/main.ts',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/database/**',
    '!**/types/**',
    '!**/*.guard.ts',
    '!**/*.listener.ts',
    '!**/*.jobs.ts',
    '!**/jobs/**',
    '!**/*scheduler*.ts',
    '!**/*.oauth.ts',
    '!**/*oauth*.ts',
    '!**/*.hook.ts',
    '!**/interfaces/**',
    '!**/*.interface.ts',
    '!**/providers/**',
    '!**/adapters/**',
  ],
  // Exclude modules without unit tests yet — narrows the denominator to tested codebases.
  // Remove entries from this list as specs are added (see coverage backlog in CI docs).
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/returns/',
    '/analytics/',
    '/sellers/',
    '/submissions/',
    '/cms/',
    '/influencers/',
    '/influencer-',
    '/invoices/',
    '/gift-cards/',
    '/uploads/',
    '/dashboard/',
    '/fulfillment/',
    '/blog/',
    '/webhooks/',
    '/themes/',
    '/publishing/',
    '/reviews/',
    '/users/',
    '/tax/',
    '/shipping/courier/',
    '/notifications/',
    '/newsletter/',
    '/marketing/',
    '/meilisearch/',
    '/procurement/',
    '/logistics/',
    '/catalog/',
    '/channels/',
    '/cache/',
    '/addresses/',
    '/wishlist/',
    '/whatsapp/',
    '/vendor-ledger/',
    '/vendor-products/',
    '/universes/',
    '/tenants/',
    '/testimonials/',
    '/templates/',
    '/taxonomy/',
    '/submissions/',
    '/social-sharing/',
    '/settlements/',
    '/return-policies/',
    '/referrals/',
    '/quests/',
    '/promotions/',
    '/performance/',
    '/rate-limit/',
    '/navigation/',
    '/monitoring/',
    '/integrations/',
    '/invoices/',
    '/geolocation/',
    '/gdpr/',
    '/gamification/',
    '/fandoms/',
    '/founding-members/',
    '/discrepancies/',
    '/digital-products/',
    '/departments/',
    '/compliance/',
    '/collections/',
    '/characters/',
    '/cancellations/',
    '/badges/',
    '/activity/',
    '/ai/',
    '/gallery/',
    '/customer-groups/',
    '/currency/',
    '/domains/',
    '/customer-groups/',
    'admin/products.service',
    'orders/order-shipping.service',
    'finance/reconciliation.service',
    'pos/sync/customer-identity-backfill.service',
    'products/products-bulk.service',
    'loyalty/loyalty-event.service',
    'loyalty/loyalty.jobs',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/../test/setup.ts'],
  transformIgnorePatterns: [
    'node_modules/(?!(@nestjs|bcrypt))',
  ],
};


