import {
  LayoutDashboard,
  Package,
  DollarSign,
  TrendingUp,
  ClipboardList,
  FileText,
  ShoppingCart,
  Users,
  Plus,
  Truck,
  Banknote,
  CreditCard,
  User,
  Target,
  Zap,
  Wallet,
  AlertTriangle,
  Settings,
  Undo2,
  ShoppingBag,
  Image,
  Megaphone,
  Library,
  BookOpen,
  Gem,
  Tag,
  Gift,
  Hourglass,
  Link,
  RefreshCw,
  Mail,
  Calendar,
  Building2,
  Store,
  Building,
  Trophy,
  Palette,
  PartyPopper,
  Star,
  CheckCircle,
  Handshake,
  Rocket,
  Map,
  Wrench,
  Search,
  Camera,
  Upload,
  Volume2,
  Radio,
  File,
  Folder,
  MessageCircle,
  Crown,
  Factory,
  Landmark,
  Ticket,
  Sparkles,
  Heart,
  XCircle,
  PenLine,
  Scale,
  IdCard,
  Receipt,
  Compass,
  Puzzle,
  Wand2,
  CircleDollarSign,
  Shield,
  Flag,
  Clock,
  Hash,
  Bell,
  Lock,
  Plug,
  Smartphone,
  MailOpen,
  ArrowLeftRight,
  Lightbulb,
  Tent,
  Globe,
  Orbit,
  HelpCircle,
  Check,
  ToggleLeft,
  Pencil,
  MailPlus,
  CheckSquare,
  Cloud,
  Info,
  Home,
  Menu,
  LogOut,
  X,
  ChevronRight,
  ArrowLeft,
  type LucideIcon,
} from 'lucide-react';
import { createElement } from 'react';

export const NAV_ICONS = {
  // Dashboards & analytics
  dashboard: LayoutDashboard,
  trending: TrendingUp,
  lightbulb: Lightbulb,

  // Commerce & products
  package: Package,
  cart: ShoppingCart,
  shoppingBag: ShoppingBag,
  store: Store,
  receipt: Receipt,
  tag: Tag,
  gift: Gift,

  // Money & payments
  dollar: DollarSign,
  banknote: Banknote,
  creditCard: CreditCard,
  wallet: Wallet,
  circleDollar: CircleDollarSign,
  landmark: Landmark,
  currencies: ArrowLeftRight,

  // Lists, documents & content
  clipboard: ClipboardList,
  fileText: FileText,
  file: File,
  folder: Folder,
  penLine: PenLine,
  pencil: Pencil,
  library: Library,
  bookOpen: BookOpen,
  scale: Scale,

  // People & roles
  users: Users,
  user: User,
  crown: Crown,
  handshake: Handshake,
  idCard: IdCard,
  ticket: Ticket,

  // Actions
  plus: Plus,
  undo: Undo2,
  refresh: RefreshCw,
  upload: Upload,
  search: Search,
  link: Link,
  check: Check,
  checkCircle: CheckCircle,
  checkSquare: CheckSquare,
  xCircle: XCircle,

  // Shipping & logistics
  truck: Truck,
  factory: Factory,
  warehouse: Building2,
  building: Building,

  // Marketing & engagement
  target: Target,
  zap: Zap,
  megaphone: Megaphone,
  volume: Volume2,
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  party: PartyPopper,
  trophy: Trophy,
  rocket: Rocket,
  gem: Gem,

  // Media & design
  image: Image,
  camera: Camera,
  palette: Palette,

  // Communication
  mail: Mail,
  mailPlus: MailPlus,
  mailOpen: MailOpen,
  message: MessageCircle,
  bell: Bell,
  smartphone: Smartphone,

  // Status & time
  hourglass: Hourglass,
  clock: Clock,
  calendar: Calendar,
  alert: AlertTriangle,

  // Config & system
  settings: Settings,
  wrench: Wrench,
  compass: Compass,
  puzzle: Puzzle,
  wand: Wand2,
  shield: Shield,
  flag: Flag,
  lock: Lock,
  plug: Plug,
  cloud: Cloud,
  hash: Hash,
  toggle: ToggleLeft,
  radio: Radio,

  // Places & navigation
  map: Map,
  globe: Globe,
  orbit: Orbit,
  tent: Tent,
  home: Home,
  menu: Menu,
  logOut: LogOut,
  help: HelpCircle,
  info: Info,
  close: X,
  chevronRight: ChevronRight,
  arrowLeft: ArrowLeft,
} as const satisfies Record<string, LucideIcon>;

export type NavIconKey = keyof typeof NAV_ICONS;

/** Create a sized icon element ready for nav menus */
export function navIcon(key: NavIconKey, className = 'w-4 h-4'): React.ReactElement {
  return createElement(NAV_ICONS[key], { className, 'aria-hidden': true });
}
