/** Assets and demo content mirrored from lawngreen-cattle reference storefront */

/** Official transparent brand marks (PNG) */
export const BRAND_LOGOS = {
  emblem: '/assets/logo-emblem.png',
  wordmark: '/assets/logo-wordmark.png',
  stacked: '/assets/logo-stacked.png',
} as const;

export const REFERENCE_ASSETS = {
  logo: BRAND_LOGOS.stacked,
  heroBanner: '/assets/hero-banner.png',
  franchiseBanners: {
    'harry-potter': '/assets/banner-harry-potter.png',
    'lord-of-the-rings': '/assets/banner-lotr.png',
    'game-of-thrones': '/assets/banner-game-of-thrones.png',
  },
  franchises: {
    'harry-potter': { name: 'Harry Potter', logo: '/assets/franchises/harry-potter.svg' },
    'game-of-thrones': { name: 'Game of Thrones', logo: '/assets/franchises/game-of-thrones.jpg', photo: true },
    'stranger-things': { name: 'Stranger Things', logo: '/assets/franchises/stranger-things.svg' },
    'lord-of-the-rings': { name: 'Lord of the Rings', logo: '/assets/franchises/lotr.svg' },
    hobbit: { name: 'The Hobbit', logo: '/assets/franchises/hobbit.svg' },
    wednesday: { name: 'Wednesday', logo: '/assets/franchises/wednesday.svg' },
    friends: { name: 'Friends', logo: '/assets/franchises/friends.svg' },
    'peaky-blinders': { name: 'Peaky Blinders', logo: '/assets/franchises/peaky-blinders.svg' },
    'star-wars': { name: 'Star Wars', logo: '/assets/franchises/star-wars.svg' },
    'squid-game': { name: 'Squid Game', logo: '/assets/franchises/squid-game.svg' },
    'anime-drama': { name: 'Anime & Drama Series', logo: '/assets/franchises/anime-drama.svg' },
    'gothic-collection': { name: 'Gothic Collection', logo: '/assets/franchises/gothic-collection.svg' },
  },
} as const;

export const REFERENCE_FRANCHISE_ORDER = [
  'harry-potter',
  'game-of-thrones',
  'stranger-things',
  'lord-of-the-rings',
  'hobbit',
  'wednesday',
  'friends',
  'peaky-blinders',
  'star-wars',
  'squid-game',
  'anime-drama',
  'gothic-collection',
] as const;

/** Demo products from reference site (Pexels) — used when API returns no items */
export const REFERENCE_DEMO_PRODUCTS = [
  {
    id: 'demo-wand-hero',
    name: 'Character wand — hero edition',
    price: 34.99,
    rrp: 39.99,
    vendor: 'Gringotts Collectibles',
    averageRating: 4,
    badge: 'sale' as const,
    image: 'https://images.pexels.com/photos/5472395/pexels-photo-5472395.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  },
  {
    id: 'demo-spell-book',
    name: 'Unofficial spell compendium',
    price: 12.99,
    rrp: 15.99,
    vendor: 'Raven Row Books',
    averageRating: 5,
    badge: 'sale' as const,
    image: 'https://images.pexels.com/photos/2565761/pexels-photo-2565761.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  },
  {
    id: 'demo-crest-pendant',
    name: 'House crest pendant — silver',
    price: 12.99,
    rrp: 17.99,
    vendor: 'Diagon Jewellers',
    averageRating: 5,
    badge: 'sale' as const,
    image: 'https://images.pexels.com/photos/1458868/pexels-photo-1458868.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  },
  {
    id: 'demo-pin-set',
    name: 'Hogwarts house enamel pin set',
    price: 8.49,
    rrp: 11.99,
    vendor: 'House Pride Pins',
    averageRating: 4,
    badge: 'sale' as const,
    image: 'https://images.pexels.com/photos/8191527/pexels-photo-8191527.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  },
  {
    id: 'demo-display-stand',
    name: 'Wand & prop display stand',
    price: 19.99,
    rrp: 27.99,
    vendor: 'Wychwood Workshop',
    averageRating: 4,
    badge: 'sale' as const,
    image: 'https://images.pexels.com/photos/4110353/pexels-photo-4110353.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  },
  {
    id: 'demo-art-print',
    name: 'Diagon Alley collectable art print',
    price: 18.0,
    vendor: 'Flourish & Blotts Framing',
    averageRating: 5,
    badge: 'new' as const,
    image: 'https://images.pexels.com/photos/7681250/pexels-photo-7681250.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  },
  {
    id: 'demo-scarf',
    name: 'House scarf — premium weave',
    price: 24.99,
    vendor: 'Crown & Cloak',
    averageRating: 4,
    badge: 'new' as const,
    image: 'https://images.pexels.com/photos/4596818/pexels-photo-4596818.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  },
  {
    id: 'demo-wand-core',
    name: 'Character wand — core collection',
    price: 42.0,
    vendor: "Ollivander's Outlet",
    averageRating: 5,
    badge: 'new' as const,
    image: 'https://images.pexels.com/photos/1784577/pexels-photo-1784577.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  },
  {
    id: 'demo-mug-duo',
    name: 'Hogwarts house mug duo',
    price: 16.5,
    vendor: 'Three Broomsticks Co.',
    averageRating: 5,
    badge: 'new' as const,
    image: 'https://images.pexels.com/photos/6061740/pexels-photo-6061740.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  },
  {
    id: 'demo-foil-print',
    name: 'Castle triptych foil print set',
    price: 32.0,
    vendor: 'Common Room Canvas',
    averageRating: 5,
    badge: 'new' as const,
    image: 'https://images.pexels.com/photos/2832084/pexels-photo-2832084.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  },
  {
    id: 'demo-necklace',
    name: 'Sterling charm necklace — celestial',
    price: 12.99,
    vendor: 'Time-Turner Trinkets',
    averageRating: 5,
    image: 'https://images.pexels.com/photos/3643925/pexels-photo-3643925.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  },
  {
    id: 'demo-wand-box',
    name: 'Character wand in collector box',
    price: 34.99,
    vendor: 'Hogsmeade Haul',
    averageRating: 4,
    image: 'https://images.pexels.com/photos/235926/pexels-photo-235926.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  },
  {
    id: 'demo-golden-egg',
    name: 'Golden egg pendant — premium metal',
    price: 64.99,
    vendor: 'Astronomy Tower',
    averageRating: 5,
    image: 'https://images.pexels.com/photos/34100748/pexels-photo-34100748.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  },
  {
    id: 'demo-desk-lamp',
    name: 'Great Hall inspired desk lamp',
    price: 64.99,
    vendor: 'Lumos & Co.',
    averageRating: 5,
    image: 'https://images.pexels.com/photos/8191512/pexels-photo-8191512.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  },
  {
    id: 'demo-gift-bundle',
    name: 'House gift bundle — deluxe',
    price: 49.99,
    vendor: 'Three Broomsticks Bundles',
    averageRating: 5,
    image: 'https://images.pexels.com/photos/5710541/pexels-photo-5710541.jpeg?auto=compress&cs=tinysrgb&w=640&h=640&fit=crop',
  },
] as const;
